name: FamiVoice
version: '${project.version}'
main: org.permadoor.famivoice.FamiVoice
api-version: '1.20'
depend: [OpenAudioMc]
permissions:
  famivoice.bypass:
    default: op
    description: Bypass the FamiVoice system so that player can join and move without being in the voicechat
